/* https://www.csvjson.com/csv2json */

var dataOriginal = [
  ("Abathur": {
    Map: "Volskaya Foundry",
    WinRate: 48.84,
    PlayRate: 9.13,
    BanRate: 4.05,
    HeroID: "Abathur",
    Role: "Support",
    Difficulty: 5,
    Point: 0,
    URLID: "Abathur"
  }),
  ("Alarak": {
    Map: "Volskaya Foundry",
    WinRate: 49.17,
    PlayRate: 37.44,
    BanRate: 28.02,
    HeroID: "Alarak",
    Role: "Melee",
    Difficulty: 4,
    Point: 0,
    URLID: "Alarak"
  }),
  ("Alexstrasza": {
    Map: "Volskaya Foundry",
    WinRate: 48.49,
    PlayRate: 12.24,
    BanRate: 2.96,
    HeroID: "Alexstrasza",
    Role: "Healer",
    Difficulty: 3,
    Point: 0,
    URLID: "Alexstrasza"
  }),
  ("Ana": {
    Map: "Volskaya Foundry",
    WinRate: 49.59,
    PlayRate: 26.27,
    BanRate: 13.5,
    HeroID: "Ana",
    Role: "Healer",
    Difficulty: 4,
    Point: 0,
    URLID: "Ana"
  }),
  ("Anduin": {
    Map: "Volskaya Foundry",
    WinRate: 45.64,
    PlayRate: 27.6,
    BanRate: 10.15,
    HeroID: "Anduin",
    Role: "Healer",
    Difficulty: 2,
    Point: 0,
    URLID: "Anduin"
  }),
  ("Anub'arak": {
    Map: "Volskaya Foundry",
    WinRate: 48.95,
    PlayRate: 15.59,
    BanRate: 4.34,
    HeroID: "Anubarak",
    Role: "Tank",
    Difficulty: 3,
    Point: 0,
    URLID: "Anub%27arak"
  }),
  ("Artanis": {
    Map: "Volskaya Foundry",
    WinRate: 47.23,
    PlayRate: 11.93,
    BanRate: 1.73,
    HeroID: "Artanis",
    Role: "Bruiser",
    Difficulty: 2,
    Point: 0,
    URLID: "Artanis"
  }),
  ("Arthas": {
    Map: "Volskaya Foundry",
    WinRate: 47.5,
    PlayRate: 13.95,
    BanRate: 2.75,
    HeroID: "Arthas",
    Role: "Tank",
    Difficulty: 3,
    Point: 0,
    URLID: "Arthas"
  }),
  ("Auriel": {
    Map: "Volskaya Foundry",
    WinRate: 52.98,
    PlayRate: 58.33,
    BanRate: 37.23,
    HeroID: "Auriel",
    Role: "Healer",
    Difficulty: 4,
    Point: 0,
    URLID: "Auriel"
  }),
  ("Azmodan": {
    Map: "Volskaya Foundry",
    WinRate: 51.1,
    PlayRate: 14.25,
    BanRate: 5.19,
    HeroID: "Azmodan",
    Role: "Ranged",
    Difficulty: 2,
    Point: 0,
    URLID: "Azmodan"
  }),
  ("Blaze": {
    Map: "Volskaya Foundry",
    WinRate: 47.88,
    PlayRate: 9.19,
    BanRate: 0.69,
    HeroID: "Blaze",
    Role: "Tank",
    Difficulty: 3,
    Point: 0,
    URLID: "Blaze"
  }),
  ("Brightwing": {
    Map: "Volskaya Foundry",
    WinRate: 48.88,
    PlayRate: 16.58,
    BanRate: 3.81,
    HeroID: "Brightwing",
    Role: "Healer",
    Difficulty: 2,
    Point: 0,
    URLID: "Brightwing"
  }),
  ("Cassia": {
    Map: "Volskaya Foundry",
    WinRate: 46.09,
    PlayRate: 4.65,
    BanRate: 0.44,
    HeroID: "Cassia",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Cassia"
  }),
  ("Chen": {
    Map: "Volskaya Foundry",
    WinRate: 47.31,
    PlayRate: 4.23,
    BanRate: 0.88,
    HeroID: "Chen",
    Role: "Bruiser",
    Difficulty: 4,
    Point: 0,
    URLID: "Chen"
  }),
  ("Cho": {
    Map: "Volskaya Foundry",
    WinRate: 46.56,
    PlayRate: 3.34,
    BanRate: 1.35,
    HeroID: "Cho",
    Role: "Tank",
    Difficulty: 5,
    Point: 0,
    URLID: "Cho"
  }),
  ("Chromie": {
    Map: "Volskaya Foundry",
    WinRate: 49.83,
    PlayRate: 13.69,
    BanRate: 2.87,
    HeroID: "Chromie",
    Role: "Ranged",
    Difficulty: 4,
    Point: 0,
    URLID: "Chromie"
  }),
  ("D.Va": {
    Map: "Volskaya Foundry",
    WinRate: 44.04,
    PlayRate: 3.12,
    BanRate: 0.2,
    HeroID: "Dva",
    Role: "Bruiser",
    Difficulty: 4,
    Point: 0,
    URLID: "D.Va"
  }),
  ("Deathwing": {
    Map: "Volskaya Foundry",
    WinRate: 56.18,
    PlayRate: 90.55,
    BanRate: 83.82,
    HeroID: "Deathwing",
    Role: "Bruiser",
    Difficulty: 2,
    Point: 0,
    URLID: "Deathwing"
  }),
  ("Deckard": {
    Map: "Volskaya Foundry",
    WinRate: 49.65,
    PlayRate: 9.75,
    BanRate: 0.9,
    HeroID: "Deckard",
    Role: "Healer",
    Difficulty: 3,
    Point: 0,
    URLID: "Deckard"
  }),
  ("Dehaka": {
    Map: "Volskaya Foundry",
    WinRate: 40.92,
    PlayRate: 3.18,
    BanRate: 0.75,
    HeroID: "Dehaka",
    Role: "Bruiser",
    Difficulty: 3,
    Point: 0,
    URLID: "Dehaka"
  }),
  ("Diablo": {
    Map: "Volskaya Foundry",
    WinRate: 46.49,
    PlayRate: 34.04,
    BanRate: 15.46,
    HeroID: "Diablo",
    Role: "Tank",
    Difficulty: 2,
    Point: 0,
    URLID: "Diablo"
  }),
  ("E.T.C.": {
    Map: "Volskaya Foundry",
    WinRate: 52.42,
    PlayRate: 45.23,
    BanRate: 20.83,
    HeroID: "Etc",
    Role: "Tank",
    Difficulty: 3,
    Point: 0,
    URLID: "E.T.C."
  }),
  ("Falstad": {
    Map: "Volskaya Foundry",
    WinRate: 50.94,
    PlayRate: 9.68,
    BanRate: 1.09,
    HeroID: "Falstad",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Falstad"
  }),
  ("Fenix": {
    Map: "Volskaya Foundry",
    WinRate: 49.47,
    PlayRate: 6.19,
    BanRate: 0.3,
    HeroID: "Fenix",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Fenix"
  }),
  ("Gall": {
    Map: "Volskaya Foundry",
    WinRate: 46.56,
    PlayRate: 2.69,
    BanRate: 0.7,
    HeroID: "Gall",
    Role: "Ranged",
    Difficulty: 4,
    Point: 0,
    URLID: "Gall"
  }),
  ("Garrosh": {
    Map: "Volskaya Foundry",
    WinRate: 48.39,
    PlayRate: 52.56,
    BanRate: 35.91,
    HeroID: "Garrosh",
    Role: "Tank",
    Difficulty: 3,
    Point: 0,
    URLID: "Garrosh"
  }),
  ("Gazlowe": {
    Map: "Volskaya Foundry",
    WinRate: 52.52,
    PlayRate: 5.95,
    BanRate: 0.65,
    HeroID: "Gazlowe",
    Role: "Melee",
    Difficulty: 3,
    Point: 0,
    URLID: "Gazlowe"
  }),
  ("Genji": {
    Map: "Volskaya Foundry",
    WinRate: 40.25,
    PlayRate: 5.22,
    BanRate: 0.82,
    HeroID: "Genji",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Genji"
  }),
  ("Greymane": {
    Map: "Volskaya Foundry",
    WinRate: 49.9,
    PlayRate: 19.96,
    BanRate: 4.26,
    HeroID: "Greymane",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Greymane"
  }),
  ("Gul'dan": {
    Map: "Volskaya Foundry",
    WinRate: 45.18,
    PlayRate: 15.58,
    BanRate: 3.59,
    HeroID: "Guldan",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Gul%27dan"
  }),
  ("Hanzo": {
    Map: "Volskaya Foundry",
    WinRate: 45.74,
    PlayRate: 13.85,
    BanRate: 2.46,
    HeroID: "Hanzo",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Hanzo"
  }),
  ("Illidan": {
    Map: "Volskaya Foundry",
    WinRate: 45.47,
    PlayRate: 4.98,
    BanRate: 0.93,
    HeroID: "Illidan",
    Role: "Melee",
    Difficulty: 4,
    Point: 0,
    URLID: "Illidan"
  }),
  ("Imperius": {
    Map: "Volskaya Foundry",
    WinRate: 46.92,
    PlayRate: 14.07,
    BanRate: 2.16,
    HeroID: "Imperius",
    Role: "Bruiser",
    Difficulty: 2,
    Point: 0,
    URLID: "Imperius"
  }),
  ("Jaina": {
    Map: "Volskaya Foundry",
    WinRate: 49.21,
    PlayRate: 22.79,
    BanRate: 5.1,
    HeroID: "Jaina",
    Role: "Ranged",
    Difficulty: 2,
    Point: 0,
    URLID: "Jaina"
  }),
  ("Johanna": {
    Map: "Volskaya Foundry",
    WinRate: 51.79,
    PlayRate: 60.26,
    BanRate: 27.11,
    HeroID: "Johanna",
    Role: "Tank",
    Difficulty: 2,
    Point: 0,
    URLID: "Johanna"
  }),
  ("Junkrat": {
    Map: "Volskaya Foundry",
    WinRate: 43.58,
    PlayRate: 10.42,
    BanRate: 1.99,
    HeroID: "Junkrat",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Junkrat"
  }),
  ("Kael'thas": {
    Map: "Volskaya Foundry",
    WinRate: 50.15,
    PlayRate: 73.64,
    BanRate: 54.68,
    HeroID: "Kaelthas",
    Role: "Ranged",
    Difficulty: 1,
    Point: 0,
    URLID: "Kael%27thas"
  }),
  ("Kel'Thuzad": {
    Map: "Volskaya Foundry",
    WinRate: 48.91,
    PlayRate: 20.71,
    BanRate: 9.92,
    HeroID: "Kelthuzad",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Kel%27Thuzad"
  }),
  ("Kerrigan": {
    Map: "Volskaya Foundry",
    WinRate: 53.44,
    PlayRate: 3.94,
    BanRate: 0.32,
    HeroID: "Kerrigan",
    Role: "Melee",
    Difficulty: 4,
    Point: 0,
    URLID: "Kerrigan"
  }),
  ("Kharazim": {
    Map: "Volskaya Foundry",
    WinRate: 49.44,
    PlayRate: 5.26,
    BanRate: 0.26,
    HeroID: "Kharazim",
    Role: "Healer",
    Difficulty: 3,
    Point: 0,
    URLID: "Kharazim"
  }),
  ("Leoric": {
    Map: "Volskaya Foundry",
    WinRate: 50.15,
    PlayRate: 14.59,
    BanRate: 2.11,
    HeroID: "Leoric",
    Role: "Bruiser",
    Difficulty: 2,
    Point: 0,
    URLID: "Leoric"
  }),
  ("Li Li": {
    Map: "Volskaya Foundry",
    WinRate: 49.87,
    PlayRate: 24.98,
    BanRate: 8.37,
    HeroID: "Lili",
    Role: "Healer",
    Difficulty: 1,
    Point: 0,
    URLID: "Li+Li"
  }),
  ("Li-Ming": {
    Map: "Volskaya Foundry",
    WinRate: 49.77,
    PlayRate: 56.39,
    BanRate: 17.8,
    HeroID: "Liming",
    Role: "Ranged",
    Difficulty: 2,
    Point: 0,
    URLID: "Li-Ming"
  }),
  ("Lt. Morales": {
    Map: "Volskaya Foundry",
    WinRate: 49.13,
    PlayRate: 9.65,
    BanRate: 2.89,
    HeroID: "Ltmorales",
    Role: "Healer",
    Difficulty: 3,
    Point: 0,
    URLID: "Lt.+Morales"
  }),
  ("Lúcio": {
    Map: "Volskaya Foundry",
    WinRate: 51.28,
    PlayRate: 24.08,
    BanRate: 6.59,
    HeroID: "Lucio",
    Role: "Healer",
    Difficulty: 3,
    Point: 0,
    URLID: "Lúcio"
  }),
  ("Lunara": {
    Map: "Volskaya Foundry",
    WinRate: 50.84,
    PlayRate: 16.8,
    BanRate: 2.42,
    HeroID: "Lunara",
    Role: "Ranged",
    Difficulty: 2,
    Point: 0,
    URLID: "Lunara"
  }),
  ("Maiev": {
    Map: "Volskaya Foundry",
    WinRate: 47.46,
    PlayRate: 6.45,
    BanRate: 1.19,
    HeroID: "Maiev",
    Role: "Melee",
    Difficulty: 4,
    Point: 0,
    URLID: "Maiev"
  }),
  ("Mal'Ganis": {
    Map: "Volskaya Foundry",
    WinRate: 52.48,
    PlayRate: 27.16,
    BanRate: 11.14,
    HeroID: "Malganis",
    Role: "Tank",
    Difficulty: 3,
    Point: 0,
    URLID: "Mal%27Ganis"
  }),
  ("Malfurion": {
    Map: "Volskaya Foundry",
    WinRate: 49.15,
    PlayRate: 12.46,
    BanRate: 1.82,
    HeroID: "Malfurion",
    Role: "Healer",
    Difficulty: 3,
    Point: 0,
    URLID: "Malfurion"
  }),
  ("Malthael": {
    Map: "Volskaya Foundry",
    WinRate: 47.48,
    PlayRate: 11.26,
    BanRate: 3.13,
    HeroID: "Malthael",
    Role: "Bruiser",
    Difficulty: 4,
    Point: 0,
    URLID: "Malthael"
  }),
  ("Medivh": {
    Map: "Volskaya Foundry",
    WinRate: 43.01,
    PlayRate: 4.59,
    BanRate: 0.63,
    HeroID: "Medivh",
    Role: "Support",
    Difficulty: 5,
    Point: 0,
    URLID: "Medivh"
  }),
  ("Mephisto": {
    Map: "Volskaya Foundry",
    WinRate: 52.87,
    PlayRate: 8.35,
    BanRate: 0.66,
    HeroID: "Mephisto",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Mephisto"
  }),
  ("Muradin": {
    Map: "Volskaya Foundry",
    WinRate: 48.56,
    PlayRate: 23.18,
    BanRate: 1.98,
    HeroID: "Muradin",
    Role: "Tank",
    Difficulty: 1,
    Point: 0,
    URLID: "Muradin"
  }),
  ("Murky": {
    Map: "Volskaya Foundry",
    WinRate: 54.77,
    PlayRate: 3.92,
    BanRate: 0.47,
    HeroID: "Murky",
    Role: "Melee",
    Difficulty: 4,
    Point: 0,
    URLID: "Murky"
  }),
  ("Nazeebo": {
    Map: "Volskaya Foundry",
    WinRate: 54.48,
    PlayRate: 24.49,
    BanRate: 2.64,
    HeroID: "Nazeebo",
    Role: "Ranged",
    Difficulty: 2,
    Point: 0,
    URLID: "Nazeebo"
  }),
  ("Nova": {
    Map: "Volskaya Foundry",
    WinRate: 44.61,
    PlayRate: 4.15,
    BanRate: 0.29,
    HeroID: "Nova",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Nova"
  }),
  ("Orphea": {
    Map: "Volskaya Foundry",
    WinRate: 49.45,
    PlayRate: 8.02,
    BanRate: 0.71,
    HeroID: "Orphea",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Orphea"
  }),
  ("Probius": {
    Map: "Volskaya Foundry",
    WinRate: 47.88,
    PlayRate: 1.71,
    BanRate: 0.24,
    HeroID: "Probius",
    Role: "Ranged",
    Difficulty: 4,
    Point: 0,
    URLID: "Probius"
  }),
  ("Qhira": {
    Map: "Volskaya Foundry",
    WinRate: 46.5,
    PlayRate: 20.47,
    BanRate: 9.8,
    HeroID: "Qhira",
    Role: "Melee",
    Difficulty: 2,
    Point: 0,
    URLID: "Qhira"
  }),
  ("Ragnaros": {
    Map: "Volskaya Foundry",
    WinRate: 52.65,
    PlayRate: 9.72,
    BanRate: 2.21,
    HeroID: "Ragnaros",
    Role: "Bruiser",
    Difficulty: 3,
    Point: 0,
    URLID: "Ragnaros"
  }),
  ("Raynor": {
    Map: "Volskaya Foundry",
    WinRate: 50.97,
    PlayRate: 19.88,
    BanRate: 1.66,
    HeroID: "Raynor",
    Role: "Ranged",
    Difficulty: 1,
    Point: 0,
    URLID: "Raynor"
  }),
  ("Rehgar": {
    Map: "Volskaya Foundry",
    WinRate: 52.72,
    PlayRate: 14.25,
    BanRate: 1.34,
    HeroID: "Rehgar",
    Role: "Healer",
    Difficulty: 3,
    Point: 0,
    URLID: "Rehgar"
  }),
  ("Rexxar": {
    Map: "Volskaya Foundry",
    WinRate: 53.95,
    PlayRate: 7.39,
    BanRate: 2.59,
    HeroID: "Rexxar",
    Role: "Bruiser",
    Difficulty: 3,
    Point: 0,
    URLID: "Rexxar"
  }),
  ("Samuro": {
    Map: "Volskaya Foundry",
    WinRate: 56.93,
    PlayRate: 6.22,
    BanRate: 1.64,
    HeroID: "Samuro",
    Role: "Melee",
    Difficulty: 3,
    Point: 0,
    URLID: "Samuro"
  }),
  ("Sgt. Hammer": {
    Map: "Volskaya Foundry",
    WinRate: 46.56,
    PlayRate: 3.2,
    BanRate: 0.76,
    HeroID: "Sgthammer",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Sgt.+Hammer"
  }),
  ("Sonya": {
    Map: "Volskaya Foundry",
    WinRate: 55.01,
    PlayRate: 14.04,
    BanRate: 1.83,
    HeroID: "Sonya",
    Role: "Bruiser",
    Difficulty: 2,
    Point: 0,
    URLID: "Sonya"
  }),
  ("Stitches": {
    Map: "Volskaya Foundry",
    WinRate: 46.98,
    PlayRate: 14.54,
    BanRate: 1.25,
    HeroID: "Stitches",
    Role: "Tank",
    Difficulty: 2,
    Point: 0,
    URLID: "Stitches"
  }),
  ("Stukov": {
    Map: "Volskaya Foundry",
    WinRate: 47.14,
    PlayRate: 17.29,
    BanRate: 4.55,
    HeroID: "Stukov",
    Role: "Healer",
    Difficulty: 3,
    Point: 0,
    URLID: "Stukov"
  }),
  ("Sylvanas": {
    Map: "Volskaya Foundry",
    WinRate: 48.96,
    PlayRate: 19.12,
    BanRate: 3.94,
    HeroID: "Sylvanas",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Sylvanas"
  }),
  ("Tassadar": {
    Map: "Volskaya Foundry",
    WinRate: 43.59,
    PlayRate: 3.2,
    BanRate: 0.29,
    HeroID: "Tassadar",
    Role: "Support",
    Difficulty: 4,
    Point: 0,
    URLID: "Tassadar"
  }),
  ("The Butcher": {
    Map: "Volskaya Foundry",
    WinRate: 55.41,
    PlayRate: 10.59,
    BanRate: 3.36,
    HeroID: "Thebutcher",
    Role: "Melee",
    Difficulty: 2,
    Point: 0,
    URLID: "The+Butcher"
  }),
  ("The Lost Vikings": {
    Map: "Volskaya Foundry",
    WinRate: 42.11,
    PlayRate: 1.31,
    BanRate: 0.48,
    HeroID: "Thelostvikings",
    Role: "Support",
    Difficulty: 5,
    Point: 0,
    URLID: "The+Lost+Vikings"
  }),
  ("Thrall": {
    Map: "Volskaya Foundry",
    WinRate: 52.46,
    PlayRate: 21.54,
    BanRate: 1.32,
    HeroID: "Thrall",
    Role: "Bruiser",
    Difficulty: 2,
    Point: 0,
    URLID: "Thrall"
  }),
  ("Tracer": {
    Map: "Volskaya Foundry",
    WinRate: 46.74,
    PlayRate: 4.15,
    BanRate: 0.71,
    HeroID: "Tracer",
    Role: "Ranged",
    Difficulty: 4,
    Point: 0,
    URLID: "Tracer"
  }),
  ("Tychus": {
    Map: "Volskaya Foundry",
    WinRate: 47.53,
    PlayRate: 11.83,
    BanRate: 2.52,
    HeroID: "Tychus",
    Role: "Ranged",
    Difficulty: 2,
    Point: 0,
    URLID: "Tychus"
  }),
  ("Tyrael": {
    Map: "Volskaya Foundry",
    WinRate: 49.67,
    PlayRate: 4.94,
    BanRate: 0.29,
    HeroID: "Tyrael",
    Role: "Tank",
    Difficulty: 3,
    Point: 0,
    URLID: "Tyrael"
  }),
  ("Tyrande": {
    Map: "Volskaya Foundry",
    WinRate: 49.86,
    PlayRate: 4.82,
    BanRate: 0.22,
    HeroID: "Tyrande",
    Role: "Healer",
    Difficulty: 3,
    Point: 0,
    URLID: "Tyrande"
  }),
  ("Uther": {
    Map: "Volskaya Foundry",
    WinRate: 55.25,
    PlayRate: 21.62,
    BanRate: 7.12,
    HeroID: "Uther",
    Role: "Healer",
    Difficulty: 3,
    Point: 0,
    URLID: "Uther"
  }),
  ("Valeera": {
    Map: "Volskaya Foundry",
    WinRate: 47.96,
    PlayRate: 5.33,
    BanRate: 0.91,
    HeroID: "Valeera",
    Role: "Melee",
    Difficulty: 4,
    Point: 0,
    URLID: "Valeera"
  }),
  ("Valla": {
    Map: "Volskaya Foundry",
    WinRate: 52.13,
    PlayRate: 25.25,
    BanRate: 3.54,
    HeroID: "Valla",
    Role: "Ranged",
    Difficulty: 2,
    Point: 0,
    URLID: "Valla"
  }),
  ("Varian": {
    Map: "Volskaya Foundry",
    WinRate: 50.11,
    PlayRate: 31.74,
    BanRate: 11.65,
    HeroID: "Varian",
    Role: "Bruiser",
    Difficulty: 1,
    Point: 0,
    URLID: "Varian"
  }),
  ("Whitemane": {
    Map: "Volskaya Foundry",
    WinRate: 51.37,
    PlayRate: 6.17,
    BanRate: 0.5,
    HeroID: "Whitemane",
    Role: "Healer",
    Difficulty: 4,
    Point: 0,
    URLID: "Whitemane"
  }),
  ("Xul": {
    Map: "Volskaya Foundry",
    WinRate: 51.55,
    PlayRate: 3.4,
    BanRate: 0.19,
    HeroID: "Xul",
    Role: "Bruiser",
    Difficulty: 3,
    Point: 0,
    URLID: "Xul"
  }),
  ("Yrel": {
    Map: "Volskaya Foundry",
    WinRate: 48.32,
    PlayRate: 4.21,
    BanRate: 0.32,
    HeroID: "Yrel",
    Role: "Bruiser",
    Difficulty: 4,
    Point: 0,
    URLID: "Yrel"
  }),
  ("Zagara": {
    Map: "Volskaya Foundry",
    WinRate: 54.45,
    PlayRate: 6.26,
    BanRate: 0.75,
    HeroID: "Zagara",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Zagara"
  }),
  ("Zarya": {
    Map: "Volskaya Foundry",
    WinRate: 49.33,
    PlayRate: 5.55,
    BanRate: 0.45,
    HeroID: "Zarya",
    Role: "Support",
    Difficulty: 4,
    Point: 0,
    URLID: "Zarya"
  }),
  ("Zeratul": {
    Map: "Volskaya Foundry",
    WinRate: 48.92,
    PlayRate: 9.73,
    BanRate: 3.97,
    HeroID: "Zeratul",
    Role: "Melee",
    Difficulty: 3,
    Point: 0,
    URLID: "Zeratul"
  }),
  ("Zul'jin": {
    Map: "Volskaya Foundry",
    WinRate: 56.05,
    PlayRate: 26.38,
    BanRate: 4.95,
    HeroID: "Zuljin",
    Role: "Ranged",
    Difficulty: 3,
    Point: 0,
    URLID: "Zul%27jin"
  })
];
